#!/bin/bash

read -p "Enter your marks: " marks

if [[ $marks -ge 80 ]]
then
	echo "You got first division"
elif [[ $marks -ge 60 ]]
then
	echo "You got second division"
elif [[ $marks -ge 40 ]]
then
	echo "You got third division"
else
	echo "You are fail"
fi










<< Symbol
Equal ->                  -eq (for number) / == (for string)
Greaterthan or qual to -> -ge
Lessthan or qual to ->    -le
Not equal to ->           -ne  (for number) / != (for string)
Greater than ->           -gt
Less than ->              -lt

Symbol
